"""empty message

Revision ID: 226f5b1a2eb4
Revises: None
Create Date: 2015-10-23 20:47:56.799469

"""

# revision identifiers, used by Alembic.
revision = '226f5b1a2eb4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('infill', sa.Integer(), nullable=False),
    sa.Column('shells', sa.Integer(), nullable=False),
    sa.Column('layer_height', sa.Numeric(), nullable=False),
    sa.Column('temperature', sa.Numeric(), nullable=False),
    sa.Column('extrude_speed', sa.String(length=16), nullable=False),
    sa.Column('print_speed', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_name')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job')
    ### end Alembic commands ###
