"""empty message

Revision ID: 28c0ed6373e2
Revises: 1f64071609af
Create Date: 2015-10-24 00:55:20.657032

"""

# revision identifiers, used by Alembic.
revision = '28c0ed6373e2'
down_revision = '1f64071609af'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('stl_file', sa.LargeBinary(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'stl_file')
    ### end Alembic commands ###
