"""empty message

Revision ID: 4d29ac5957cd
Revises: 226f5b1a2eb4
Create Date: 2015-10-23 23:07:26.480347

"""

# revision identifiers, used by Alembic.
revision = '4d29ac5957cd'
down_revision = '226f5b1a2eb4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql



def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job', 'layer_height', type_=mysql.DECIMAL(precision=11, scale=2))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
